import os
import requests
import base64
from dotenv import load_dotenv

load_dotenv()

def post_to_linkedin(content: str, image_base64: str = None) -> bool:
    access_token = os.getenv("LINKEDIN_ACCESS_TOKEN")
    urn = os.getenv("LINKEDIN_URN")
    
    if not access_token or not urn:
        raise ValueError("LINKEDIN_ACCESS_TOKEN or LINKEDIN_URN is missing. Please configure your .env file.")
        
    headers = {
        "Authorization": f"Bearer {access_token}",
        "X-Restli-Protocol-Version": "2.0.0",
        "Content-Type": "application/json"
    }

    # Step 1: Upload image if provided
    asset_urn = None
    if image_base64:
        try:
            image_bytes = base64.b64decode(image_base64)
            # Register upload
            register_payload = {
                "registerUploadRequest": {
                    "recipes": ["urn:li:digitalmediaRecipe:feedshare-image"],
                    "owner": urn,
                    "serviceRelationships": [{"relationshipType": "OWNER", "identifier": "urn:li:userGeneratedContent"}]
                }
            }
            reg_resp = requests.post("https://api.linkedin.com/v2/assets?action=registerUpload", headers=headers, json=register_payload)
            if reg_resp.status_code in [200, 201]:
                reg_data = reg_resp.json()
                upload_url = reg_data["value"]["uploadMechanism"]["com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest"]["uploadUrl"]
                asset_urn = reg_data["value"]["asset"]
                
                # Upload bytes
                upload_headers = {
                    "Authorization": f"Bearer {access_token}"
                }
                upload_resp = requests.put(upload_url, headers=upload_headers, data=image_bytes)
                if upload_resp.status_code not in [200, 201]:
                    print("Failed to upload image bytes to LinkedIn:", upload_resp.status_code, upload_resp.text)
                    asset_urn = None
            else:
                print("Failed to register image upload:", reg_resp.status_code, reg_resp.text)
        except Exception as e:
            print("Error uploading image:", e)

    # Step 2: Prepare Share Content
    share_content = {
        "shareCommentary": {
            "text": content
        },
        "shareMediaCategory": "NONE"
    }
    
    if asset_urn:
        share_content["shareMediaCategory"] = "IMAGE"
        share_content["media"] = [
            {
                "status": "READY",
                "description": {"text": "Image generated by AI-Post"},
                "media": asset_urn,
                "title": {"text": "Generated Image"}
            }
        ]
    
    payload = {
        "author": urn,
        "lifecycleState": "PUBLISHED",
        "specificContent": {
            "com.linkedin.ugc.ShareContent": share_content
        },
        "visibility": {
            "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
        }
    }
        
    url = "https://api.linkedin.com/v2/ugcPosts"
    response = requests.post(url, headers=headers, json=payload)
    
    if response.status_code == 201:
        print("Successfully posted to LinkedIn!")
        return True
    else:
        print(f"Failed to post to LinkedIn. Status Code: {response.status_code}")
        print(f"Response: {response.text}")
        return False
